### PR TITLE
LPD-27996

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:db-partition

**Comment by marianoalvarosaiz** [comment]
ci:report:16503843

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:report:16600491

**Comment by marianoalvarosaiz** [comment]
ci:report:16600491

**Comment by marianoalvarosaiz** [comment]
ci:report:16600491

**Comment by achaparro** [comment]
@marianoalvarosaiz if relevant passes, and db partition passed, please, send to brian

**Comment by achaparro** [comment]
ci:report:16637094

**Comment by marianoalvarosaiz** [comment]
ci:report:16637094

**Comment by marianoalvarosaiz** [comment]
ci:report:16637094

**Comment by marianoalvarosaiz** [comment]
ci:report:16637094

**Comment by marianoalvarosaiz** [comment]
Supposed unique failure tests are not related (they all are MySQL tests)

**Comment by marianoalvarosaiz** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151356

**Pull request closed without merging**
