### PR TITLE
LPS-77562 Provide a better description for debugging purposes.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
ci:close

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
ci:stop

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by crodriguezy** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
ci:stop

**Pull request closed without merging**
