### PR TITLE
LPS-78406

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
cleaner solution

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by arthurchan35** [comment]
@marianoalvarosaiz 
We have eventually decided to do the refactoring, so that sharePointFilter is not a child of secureFilter, like what you also mentioned before.
I am not super familiar with SecureFIlter implementaion, but as far as I can see it's fine to take out everything from secureFilter and make a new base class.
See if you like it

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/hhuijser/liferay-portal/pull/3208. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/562b411c8380~2...562b411c8380) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
