### PR TITLE
LPS-72931 semantic versioning

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by JavierMoral** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
@JavierMoral bump!
I pushed a new commit so please upgrade your local copy ☝️

**Comment by csierra** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
see https://github.com/topolik/liferay-portal/pull/448

**Pull request closed without merging**
