### PR TITLE
LPS-138464

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:relevant

@marianoalvarosaiz - I am re-running this, this will fail due to this error:
https://liferay.slack.com/archives/C19PWQ74J/p1648484921625339?thread_ts=1648463797.215559&cid=C19PWQ74J

Thanks!

**Comment by marianoalvarosaiz** [comment]
Thanks a lot @michaelhashimoto

**Pull request closed without merging**
