### PR TITLE
LPS-104365

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-104365

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/8665. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Thanks a lot @holatuwol!

**Pull request closed without merging**
