### PR TITLE
LPS-109189 Apply index on startup for modules too

### PR DESCRIPTION
**Pull request by achaparro**
@marianoalvarosaiz I made some minor changes, please take a look.

The only pending thing is that this deserves unit or integration tests, do you have time to implement them?

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
> @marianoalvarosaiz I made some minor changes, please take a look.
> 
> The only pending thing is that this deserves unit or integration tests, do you have time to implement them?

@achaparro You mean, tests just for your changes? Or tests for everything?

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/marianoalvarosaiz/liferay-portal/pull/881. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/4dae963c4160~1...4dae963c4160) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/liferay-uniform/liferay-portal/pull/676. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/4dae963c4160~1...4dae963c4160) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
