### PR TITLE
LPS-78406

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See discussion here: https://github.com/hhuijser/liferay-portal/pull/3200

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
Hi @arthurchan35,
 sorry for my late reply. About the current PR:

1. It makes one of SecureFilter's tests fail. It should be adapted to the new code.
2. I don't believe that hoping a method, _SecureFilter.setFilterEnabled(false)_, to never be called is a secure way to design code. Is like leaving private attributes as public willing that nobody uses them to assign incorrect values. Remember that we can try to ensure that nobody commits code disabling SecureFilter (which, besides, is like using a sledgehammer to crack a nut), but what about customer's code?
3. I don't undertand why my SharepointFilterTest class was completely ignored in the PR.

Honestly, IMHO the only totally secure ways I see to change the code are the ones I suggested (one of them even implemented), if you still don't feel OK about them feel free to discard them and send this new one, but I will express my concerns because it isn't safe.

Kind regards.

**Pull request closed without merging**
