### PR TITLE
LPS-138464

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by Esther-OC** [comment]
Starting review.

**Comment by sergiojimcos** [comment]
Starting review

**Comment by sergiojimcos** [comment]
ci:bundle

**Comment by sergiojimcos** [comment]
ci:test:bundle

**Comment by sergiojimcos** [comment]
Hi @marianoalvarosaiz as I have seen in the  Report of `ci:test:relevant` those failed tests comes from a [test update](https://issues.liferay.com/browse/LPS-142280) that is still in progress. I think we can manually move forward as issues seem not be related to the PR or the tests (Failed prior to running test, semantic-versioning-jdk8/0/0 as well as the test update that I mentioned). For that reason I think that they should not be related to this PR

Failed prior to running test
--




Failed prior to running test
--

**Comment by marianoalvarosaiz** [comment]
@sergiojimcos thanks a lot for your help and effort.

**Comment by marianoalvarosaiz** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/110380

**Pull request closed without merging**
