### PR TITLE
[TS] LPS-180299 (Pending integration test)

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @marianoalvarosaiz,

This is a PR that aims to add a requested integration test by Brian.

Could you please review it? If you think that this PR should be sent elsewhere or further clarifications are needed for this review, please, let me know.

Thanks!

https://liferay.atlassian.net/browse/LPS-180299

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
@dacousalr LGTM. Feel free to send to the liferay-core-infra user.

**Comment by dacousalr** [comment]
Thanks @marianoalvarosaiz!

Sent to https://github.com/liferay-core-infra/liferay-portal/pull/6472

**Pull request closed without merging**
