### PR TITLE
LPS-190886

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@marianoalvarosaiz, the current changes `removeCache(String)` are conflicted with https://liferay.atlassian.net/browse/LPS-115420. The old version is as this https://github.com/marianoalvarosaiz/liferay-portal/blob/2b4efa5548471c341e474a764a31fdd3be6e48a1/modules/util/portal-tools-service-builder/src/main/resources/com/liferay/portal/tools/service/builder/dependencies/persistence_impl.ftl#L2925-L2929 LPS-115420 might miss the related fix in `ModelPersistenceImpl#clearCache()`.  The commit aab0b27d4f8a8fcfd0402171e184e017d4e45ccb added https://github.com/marianoalvarosaiz/liferay-portal/blob/2b4efa5548471c341e474a764a31fdd3be6e48a1/modules/util/portal-tools-service-builder/src/main/resources/com/liferay/portal/tools/service/builder/dependencies/persistence_impl.ftl#L455-L457. I think `finderCache.clearCache(clazz)` should be unnecessary in the `ModelPersistenceImpl#clearCache()`

Based on LPS-115420, the current pr adds it back. It seems a little weird. Due to there isn't any explicit issue for the `removeCache(String)`, I prefer not handling it. And this also belongs to the different issue, please separate it to handle if necessary.

**Comment by marianoalvarosaiz** [comment]
@yuhai you mean generating a different fix to accomplish the ftl change? 

If so, what should I do with the _notifyFinderCache method? Because I'm modifying its arguments here 67c70f6b8b83e8909335b265aca9fee596767ffc and I find very weird sending the FinderCache removal across the cluster, specially when we send only the FinderCache remove, but not the EntityCache remove that is triggers everything.

**Comment by yuhai** [comment]
@marianoalvarosaiz,

> you mean generating a different fix to accomplish the ftl change?

Yes. But I am not sure if the behavior is right. If doing this, it will be conflicted with LPS-115420. We need to confirm it.

For `EntityCacheImpl`, you may keep the original logic and only remove `_notifyFinderCache()` from `notifyPortalCacheRemoved()` and `dispose()`. In addition, remove `finderCacheImpl.dispose()` from [_notify()](https://github.com/yuhai/liferay-portal/blob/LPS-194731/modules/apps/portal-cache/portal-cache-impl/src/main/java/com/liferay/portal/cache/internal/dao/orm/EntityCacheImpl.java#L342-L344)

**Pull request closed without merging**
