### PR TITLE
LPS-199724 Extract and Insert DB Partition Virtual Instance events

### PR DESCRIPTION
**Pull request by achaparro**
Hey @marianoalvarosaiz,

The logic looks good, I have just made a few small changes:
- Renaming from Company to VirtualInstance and from Activate/Deactivate to Insert/Extract since the concept of activating companies  already exist
- Add new non-required parameter when activating: new-webId, new-name, new-hostName. All of them can change during that process.
- I removed the code that deletes the company since it can be confused for Brian (I know I asked for this, sorry)

I would like to ask you a few things:
- Tests, we should create tests at least for verifying the configuration is removed when activating and deactivating. If it can be useful, we created similar tests with ComponentEnabler and DBPartitioning in UpgradeManagerTest
- I was testing the code and we do remove the configuration file but not the configuration record in the database. To avoid issues we should remove it too.
- What do you think about having a parent class for both listeners to avoid replicating the deleteConfiguration method? is not a public method for this already?

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:stable

**Comment by marianoalvarosaiz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/liferay-uniform/liferay-portal/pull/1507. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/e0070f8074e7~4...e0070f8074e7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
