### PR TITLE
LPD-20641 CAST functions refactor

### PR DESCRIPTION
**Pull request by achaparro**
Hi @marianoalvarosaiz,

Please, take a look at my commits, we missed the case where CAST is called inside CAST function.

Can you check if the changes are ok and apply similar tests for CAST_TEXT and CAST_CLOB_TEXT? We need to cover:
- Calling CAST twice in the same statement
- Calling CAST inside CAST
- Having group parenthesis inside the CAST call.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/marianoalvarosaiz/liferay-portal/pull/1181. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/9160ee04fc8c~3...9160ee04fc8c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/liferay-uniform/liferay-portal/pull/1889. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/613a971c8f11~3...613a971c8f11) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
