### PR TITLE
LPS-125162

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz see my comment in https://github.com/brianchandotcom/liferay-portal/pull/100075

**Comment by marianoalvarosaiz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/marianoalvarosaiz/liferay-portal/pull/474. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/a1181019bacc~6...a1181019bacc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Pull request submitted to https://github.com/marianoalvarosaiz/liferay-portal/pull/475. [See changes here.](https://github.com/marianoalvarosaiz/liferay-portal/compare/a1181019bacc~6...a1181019bacc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
